services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: docker-sql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ci_cd_test
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 30s
      retries: 10

  nestapp:
    container_name: nestApp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MYSQL_HOST: mysql # Docker Compose의 MySQL 서비스 이름
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: ci_cd_test
    depends_on:
      - mysql
    command:
      [
        'sh',
        '-c',
        'until nc -z myslq 3306; do eche Waiting for Mysql; sleep 5; done',
      ]
