version: '3.8'

services:
  nestapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MYSQL_HOST: mysql  # Docker Compose의 MySQL 서비스 이름
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: mydb
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
    ports:
      - '3306:3306'