services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: docker-sql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ci_cd_test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
  nestapp:
    container_name: nestApp
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      MYSQL_HOST: ${dbHost} # Docker Compose의 MySQL 서비스 이름
      MYSQL_USER: ${dbUser}
      MYSQL_PASSWORD: ${dbPassword}
      MYSQL_DATABASE: ${database}
      # MYSQL_HOST: 192.168.0.9 # Docker Compose의 MySQL 서비스 이름
      # MYSQL_USER: docker
      # MYSQL_PASSWORD: 1234
      # MYSQL_DATABASE: docker-test
    # command:
    #   ['./wait-for-it.sh', 'docker-sql:3306', '--', 'node', 'dist/src/main.js']
  front:
    container_name: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - nestapp
    ports:
      - "3333:80"
