name: CI/CD Pipeline for Nest.js and MySQL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and Run Docker Compose
        run: |
          docker-compose up -d --build

      - name: Wait for the app to be ready
        run: |
          for i in {1..30}; do curl -f http://localhost:3000/ && break || sleep 5; done

      - name: Test Application
        run: |
          curl http://localhost:3000/  # 원하는 엔드포인트로 확인

      - name: Stop and Remove Containers
        if: always() # 항상 실행
        run: |
          docker-compose down
