name: Release on Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Determine next version
        id: determine_next_version
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CICD_TEST_TOKEN }}
          script: |
            const previousTags = context.repo.tags.map(tag => tag.name);
            const latestTag = previousTags.sort((a, b) => b.localeCompare(a))[0];
            const versionParts = latestTag ? latestTag.match(/^v(\d+)\.(\d+)\.(\d+)$/) : [0, 0, 0];
            const [major, minor, patch] = versionParts.slice(1).map(Number);
            const nextVersion = `v${major}.${minor}.${patch + 1}`;
            console.log(nextVersion);
            core.setOutput('nextVersion', nextVersion);
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CICD_TEST_TOKEN }}
